node ("master"){
	def workspace = pwd()
	def script_location = "${workspace}@script"
	def COMMON_LIB_LOCATION = "${script_location}/bin"
	load "${script_location}/pipelines/jenkins/jenkins.properties"
	
	stage('BuildAndDeploy') {
		withEnv(["api_project=${api_project}","apigateway_qa_url=${apigateway_qa_url}","apigateway_qa_username=${apigateway_qa_username}","apigateway_qa_password=${apigateway_qa_password}","bin_loc=${COMMON_LIB_LOCATION}"]) {

        dir("$bin_loc"){		
		  sh '''
		     source common.lib; import_api $api_project $apigateway_qa_url $apigateway_qa_username $apigateway_qa_password
		   '''
		 }
	  }
	}
	
	stage('Test') {
	 
	}
	
	stage('Rollout') {
	
	}
   
}