node ("VMYAIBVT03L"){

	def workspace = pwd()
	def script_location = "${workspace}/apigateway"
	def COMMON_LIB_LOCATION = "${script_location}/bin"
	load "${script_location}/pipelines/jenkins/jenkins.properties"
	

   stage('Checkout') {
     checkout([$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'apigateway']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/SoftwareAG/webmethods-api-gateway-devops.git']]])
   }

	stage('BuildAndDeploy') {
		withEnv(["api_project=${api_project}","apigateway_qa_url=${apigateway_qa_url}","apigateway_qa_username=${apigateway_qa_username}","apigateway_qa_password=${apigateway_qa_password}","bin_loc=${COMMON_LIB_LOCATION}"]) {

        dir("$bin_loc"){		
		  sh '''
		     source $bin_loc/common.lib; import_api $api_project $apigateway_qa_url $apigateway_qa_username $apigateway_qa_password
		   '''
		 }
	  }
	}
	
   stage('Test') {
	withEnv(["test_suite=${test_suite}","apigateway_qa_url=${apigateway_qa_url}","bin_loc=${COMMON_LIB_LOCATION}","script_location=${script_location}"]) {
	   def environment_file_loc = "${script_location}/tests/environment/qa_environment.json"
	   def results_file = "${script_location}/Results"
		dir("$bin_loc"){		
			  sh '''
				 source $bin_loc/common.lib; run_test_suite $test_suite $env_file $apigateway_qa_url $results_file
			   '''
			 }
		  }
	}
	
	stage('Rollout') {
	withEnv(["test_suite=${test_suite}","apigateway_qa_url=${apigateway_qa_url}","bin_loc=${COMMON_LIB_LOCATION}","script_location=${script_location}"]) {
	   def environment_file_loc = "${script_location}/tests/environment/qa_environment.json"
		dir("$bin_loc"){		
			  sh '''
				 source $bin_loc/common.lib; promote_api $test_suite $env_file $apigateway_qa_url $results_file "httpInvokeUrl=$apigateway_server_url;buildNumber=${currentBuild.number}
			   '''
			 }
		  }
	}
   
}